import 'models.dart';

List<DataModel> myData = [
  DataModel(id: 1, name: 'Ammar', email: 'ammar@gmail.com'),
  DataModel(id: 2, name: 'Ammar2', email: 'ammar@gmail.com2'),
  DataModel(id: 3, name: 'Ammar3', email: 'ammar@gmail.com3'),
  DataModel(id: 4, name: 'Ammar4', email: 'ammar@gmail.com4'),
  DataModel(id: 5, name: 'Ammar5', email: 'ammar@gmail.com5'),
  DataModel(id: 6, name: 'Ammar6', email: 'ammar@gmail.com6'),
  DataModel(id: 7, name: 'Ammar7', email: 'ammar@gmail.com7'),
  DataModel(id: 8, name: 'Ammar8', email: 'ammar@gmail.com8'),
  DataModel(id: 9, name: 'Ammar9', email: 'ammar@gmail.com9'),
  DataModel(id: 10, name: 'Ammar10', email: 'ammar@gmail.com10'),
  DataModel(id: 11, name: 'Ammar11', email: 'ammar@gmail.com11'),
  DataModel(id: 12, name: 'Ammar12', email: 'ammar@gmail.com12'),
];

List<Order> sampleOrders = [
  Order(
    salesOrder: 'SO1',
    soldToParty: 'Party1',
    soldToPartyName: 'Party Name 1',
    overallSDProcessStatus: 'Completed',
    transactionCurrency: 'USD',
    totalNetAmount: 1500.75,
    salesOrderType: 'Online',
    creationDate: DateTime(2023, 5, 20),
  ),
  Order(
    salesOrder: 'SO2',
    soldToParty: 'Party2',
    soldToPartyName: 'Party Name 2',
    overallSDProcessStatus: 'Pending',
    transactionCurrency: 'EUR',
    totalNetAmount: 2300.00,
    salesOrderType: 'Retail',
    creationDate: DateTime(2023, 4, 18),
  ),
  Order(
    salesOrder: 'SO3',
    soldToParty: 'Party3',
    soldToPartyName: 'Party Name 3',
    overallSDProcessStatus: 'Cancelled',
    transactionCurrency: 'JPY',
    totalNetAmount: 1200.50,
    salesOrderType: 'Wholesale',
    creationDate: DateTime(2023, 3, 15),
  ),
  Order(
    salesOrder: 'SO4',
    soldToParty: 'Party4',
    soldToPartyName: 'Party Name 4',
    overallSDProcessStatus: 'Completed',
    transactionCurrency: 'USD',
    totalNetAmount: 5400.25,
    salesOrderType: 'Retail',
    creationDate: DateTime(2023, 2, 10),
  ),
  Order(
    salesOrder: 'SO5',
    soldToParty: 'Party5',
    soldToPartyName: 'Party Name 5',
    overallSDProcessStatus: 'Pending',
    transactionCurrency: 'EUR',
    totalNetAmount: 2700.00,
    salesOrderType: 'Online',
    creationDate: DateTime(2023, 1, 25),
  ),
  Order(
    salesOrder: 'SO6',
    soldToParty: 'Party6',
    soldToPartyName: 'Party Name 6',
    overallSDProcessStatus: 'Cancelled',
    transactionCurrency: 'JPY',
    totalNetAmount: 880.75,
    salesOrderType: 'Wholesale',
    creationDate: DateTime(2022, 12, 12),
  ),
  Order(
    salesOrder: 'SO7',
    soldToParty: 'Party7',
    soldToPartyName: 'Party Name 7',
    overallSDProcessStatus: 'Completed',
    transactionCurrency: 'USD',
    totalNetAmount: 3300.50,
    salesOrderType: 'Retail',
    creationDate: DateTime(2022, 11, 7),
  ),
  Order(
    salesOrder: 'SO8',
    soldToParty: 'Party8',
    soldToPartyName: 'Party Name 8',
    overallSDProcessStatus: 'Pending',
    transactionCurrency: 'EUR',
    totalNetAmount: 4100.00,
    salesOrderType: 'Online',
    creationDate: DateTime(2022, 10, 23),
  ),
  Order(
    salesOrder: 'SO9',
    soldToParty: 'Party9',
    soldToPartyName: 'Party Name 9',
    overallSDProcessStatus: 'Cancelled',
    transactionCurrency: 'JPY',
    totalNetAmount: 1950.25,
    salesOrderType: 'Wholesale',
    creationDate: DateTime(2022, 9, 15),
  ),
  Order(
    salesOrder: 'SO10',
    soldToParty: 'Party10',
    soldToPartyName: 'Party Name 10',
    overallSDProcessStatus: 'Completed',
    transactionCurrency: 'USD',
    totalNetAmount: 6500.75,
    salesOrderType: 'Retail',
    creationDate: DateTime(2022, 8, 20),
  ),
  Order(
    salesOrder: 'SO11',
    soldToParty: 'Party11',
    soldToPartyName: 'Party Name 11',
    overallSDProcessStatus: 'Pending',
    transactionCurrency: 'EUR',
    totalNetAmount: 2850.00,
    salesOrderType: 'Online',
    creationDate: DateTime(2022, 7, 25),
  ),
  Order(
    salesOrder: 'SO12',
    soldToParty: 'Party12',
    soldToPartyName: 'Party Name 12',
    overallSDProcessStatus: 'Cancelled',
    transactionCurrency: 'JPY',
    totalNetAmount: 1000.50,
    salesOrderType: 'Wholesale',
    creationDate: DateTime(2022, 6, 15),
  ),
  Order(
    salesOrder: 'SO13',
    soldToParty: 'Party13',
    soldToPartyName: 'Party Name 13',
    overallSDProcessStatus: 'Completed',
    transactionCurrency: 'USD',
    totalNetAmount: 3600.25,
    salesOrderType: 'Retail',
    creationDate: DateTime(2022, 5, 10),
  ),
  Order(
    salesOrder: 'SO14',
    soldToParty: 'Party14',
    soldToPartyName: 'Party Name 14',
    overallSDProcessStatus: 'Pending',
    transactionCurrency: 'EUR',
    totalNetAmount: 4900.00,
    salesOrderType: 'Online',
    creationDate: DateTime(2022, 4, 23),
  ),
  Order(
    salesOrder: 'SO15',
    soldToParty: 'Party15',
    soldToPartyName: 'Party Name 15',
    overallSDProcessStatus: 'Cancelled',
    transactionCurrency: 'JPY',
    totalNetAmount: 2250.75,
    salesOrderType: 'Wholesale',
    creationDate: DateTime(2022, 3, 19),
  ),
  Order(
    salesOrder: 'SO16',
    soldToParty: 'Party16',
    soldToPartyName: 'Party Name 16',
    overallSDProcessStatus: 'Completed',
    transactionCurrency: 'USD',
    totalNetAmount: 5750.50,
    salesOrderType: 'Retail',
    creationDate: DateTime(2022, 2, 20),
  ),
  Order(
    salesOrder: 'SO17',
    soldToParty: 'Party17',
    soldToPartyName: 'Party Name 17',
    overallSDProcessStatus: 'Pending',
    transactionCurrency: 'EUR',
    totalNetAmount: 3200.00,
    salesOrderType: 'Online',
    creationDate: DateTime(2022, 1, 25),
  ),
  Order(
    salesOrder: 'SO18',
    soldToParty: 'Party18',
    soldToPartyName: 'Party Name 18',
    overallSDProcessStatus: 'Cancelled',
    transactionCurrency: 'JPY',
    totalNetAmount: 1340.25,
    salesOrderType: 'Wholesale',
    creationDate: DateTime(2021, 12, 15),
  ),
  Order(
    salesOrder: 'SO19',
    soldToParty: 'Party19',
    soldToPartyName: 'Party Name 19',
    overallSDProcessStatus: 'Completed',
    transactionCurrency: 'USD',
    totalNetAmount: 7100.75,
    salesOrderType: 'Retail',
    creationDate: DateTime(2021, 11, 10),
  ),
  Order(
    salesOrder: 'SO20',
    soldToParty: 'Party20',
    soldToPartyName: 'Party Name 20',
    overallSDProcessStatus: 'Pending',
    transactionCurrency: 'EUR',
    totalNetAmount: 2750.00,
    salesOrderType: 'Online',
    creationDate: DateTime(2021, 10, 25),
  ),
  Order(
    salesOrder: 'SO21',
    soldToParty: 'Party21',
    soldToPartyName: 'Party Name 21',
    overallSDProcessStatus: 'Cancelled',
    transactionCurrency: 'JPY',
    totalNetAmount: 1050.50,
    salesOrderType: 'Wholesale',
    creationDate: DateTime(2021, 9, 15),
  ),
  Order(
    salesOrder: 'SO22',
    soldToParty: 'Party22',
    soldToPartyName: 'Party Name 22',
    overallSDProcessStatus: 'Completed',
    transactionCurrency: 'USD',
    totalNetAmount: 4600.25,
    salesOrderType: 'Retail',
    creationDate: DateTime(2021, 8, 20),
  ),
  Order(
    salesOrder: 'SO23',
    soldToParty: 'Party23',
    soldToPartyName: 'Party Name 23',
    overallSDProcessStatus: 'Pending',
    transactionCurrency: 'EUR',
    totalNetAmount: 3600.00,
    salesOrderType: 'Online',
    creationDate: DateTime(2021, 7, 25),
  ),
  Order(
    salesOrder: 'SO24',
    soldToParty: 'Party24',
    soldToPartyName: 'Party Name 24',
    overallSDProcessStatus: 'Cancelled',
    transactionCurrency: 'JPY',
    totalNetAmount: 2550.75,
    salesOrderType: 'Wholesale',
    creationDate: DateTime(2021, 6, 15),
  ),
  Order(
    salesOrder: 'SO25',
    soldToParty: 'Party25',
    soldToPartyName: 'Party Name 25',
    overallSDProcessStatus: 'Completed',
    transactionCurrency: 'USD',
    totalNetAmount: 5900.50,
    salesOrderType: 'Retail',
    creationDate: DateTime(2021, 5, 20),
  ),
];
